---
kind: List
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: hello-hapi
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: hello-hapi
          tier: backend
        name: hello-hapi
      spec:
        containers:
        - name: hello-hapi
          image: rockyj/hello-hapi:0.0.1
          env:
          - name: NODE_ENV
            value: production
          ports:
          - containerPort: 3000
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: hello-hapi
      tier: backend
    name: hello-hapi
  spec:
    ports:
    - port: 80
      targetPort: 3000
    selector:
      app: hello-hapi
    type: NodePort
